<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$roleIds = isset($data['role_based_navigation_role_ids']) ? $data['role_based_navigation_role_ids'] : null;
$formId = uniqid('_rbn');
?>
<div id="<?php echo $formId?>" style="font-weight: normal;">
	<label style="font-weight: bold;"><?php echo $translate('Roles filter'); ?></label>
	<?php echo $this->navRoleSelect([
            'name' => 'role_based_navigation_role_ids',
            'attributes' => [
                'id' => 'role_select' . $formId,
                'class' => 'chosen-select',
                'multiple' => 'multiple',
                'value' => $roleIds,
                'data-name' => 'role_based_navigation_role_ids',
                'data-placeholder' => 'Select role…', // @translate
                'data-collection-action' => 'replace'
            ]
        ]);
    ?>
    <script type="text/javascript">
    	console.log('test');
    	// This gets called each time jsTree is redrawn
    	// So we need to delete possibly existing chosen nodes
    	// FIXME : Yet still, moving a node disables the Chosen selector...
    	// Need to register an event to jsTree
    	// Need to keep a global list of selectors and update them based on jstree events
		$('#role_select<?php echo $formId; ?>_chosen').remove();
        $('#role_select<?php echo $formId; ?>').chosen(chosenOptions);
        $('.jstree-editlink-container').css('overflow', 'visible');
        $('#role_select<?php echo $formId; ?>').on('change', function(evt, params) {
        	if (params.selected) {
        	    $('#role_select<?php echo $formId; ?> option[value=' + params.selected + ']').attr('selected','selected');
        	}
        	if (params.deselected) {
        	    $('#role_select<?php echo $formId; ?> option[value=' + params.deselected + ']').removeAttr('selected');
        	}
        });
    </script>
</div>